"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup
from src.consts import Strings 

pkgs = []
with open('requirements.txt', 'r') as f:
    for line in f:
        pkg = line.strip().replace('-', '_')
        pkgs.append(pkg)
print(pkgs)

APP = ["app.py"]
DATA_FILES = ['resources']
OPTIONS = {
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
    },
    'packages': pkgs,
    'iconfile':'./nonfree/app-icon.icns',
}

setup(
    name=Strings.APP_TITLE,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
