[hue]
bridge_ip = ""
default_light_id = "1"

[hue.focus]
rgb = [255, 200 ,0]
brightness=254
saturation=254

[hue.relax]
rgb = [0, 0 ,0]
brightness=0
saturation=254

[hue.zone]
rgb = [255, 0, 0]
brightness=254
saturation=254

[hue.meeting]
rgb = [255, 0, 255]
brightness=254
saturation=254

[pomodoro]
focus=25
relax=5
break=15
break_after_pomo=4
